# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: laravel_db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: always
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - .:/var/www
    depends_on:
      - db
      - app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  python:
    image: python:3.9-slim
    container_name: laravel_python
    working_dir: /app
    volumes:
      - ./python-service:/app # Mount the python directory
    command: sh -c "pip install -r requirements.txt && gunicorn --bind 0.0.0.0:5000 main:app"
    ports:
      - "5000:5000" # Expose port for Python API
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
